// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qlgx.Data;

#nullable disable

namespace Qlgx.Data.Migrations
{
    [DbContext(typeof(QlgxDbContext))]
    [Migration("20260906235006_ThemRangBuocMotChongMotVo")]
    partial class ThemRangBuocMotChongMotVo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qlgx.Domain.Entities.BiTichChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DotBiTichId")
                        .HasColumnType("uuid")
                        .HasColumnName("dot_bi_tich_id");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bi_tich_chi_tiet");

                    b.HasIndex("DotBiTichId")
                        .HasDatabaseName("ix_bi_tich_chi_tiet_dot_bi_tich_id");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_bi_tich_chi_tiet_giao_dan_id");

                    b.HasIndex("GiaoXuId", "DotBiTichId", "GiaoDanId")
                        .IsUnique()
                        .HasDatabaseName("ix_bi_tich_chi_tiet_giao_xu_id_dot_bi_tich_id_giao_dan_id");

                    b.ToTable("bi_tich_chi_tiet");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.BoDemMa", b =>
                {
                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("TenBang")
                        .HasColumnType("text")
                        .HasColumnName("ten_bang");

                    b.Property<int>("GiaTriCuoi")
                        .HasColumnType("integer")
                        .HasColumnName("gia_tri_cuoi");

                    b.HasKey("GiaoXuId", "TenBang")
                        .HasName("pk_bo_dem_ma");

                    b.ToTable("bo_dem_ma");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.CauHinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GiaTri")
                        .HasColumnType("text")
                        .HasColumnName("gia_tri");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("MaCauHinh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ma_cau_hinh");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cau_hinh");

                    b.HasIndex("GiaoXuId", "MaCauHinh")
                        .IsUnique()
                        .HasDatabaseName("ix_cau_hinh_giao_xu_id_ma_cau_hinh");

                    b.ToTable("cau_hinh");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChiTietHoiDoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<Guid>("HoiDoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoi_doan_id");

                    b.Property<int>("MaChiTietHoiDoanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_chi_tiet_hoi_doan_cu");

                    b.Property<DateOnly?>("NgayRaHoiDoan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ra_hoi_doan");

                    b.Property<DateOnly?>("NgayVaoHoiDoan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_hoi_doan");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VaiTro")
                        .HasColumnType("text")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id")
                        .HasName("pk_chi_tiet_hoi_doan");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_chi_tiet_hoi_doan_giao_dan_id");

                    b.HasIndex("HoiDoanId")
                        .HasDatabaseName("ix_chi_tiet_hoi_doan_hoi_doan_id");

                    b.HasIndex("GiaoXuId", "MaChiTietHoiDoanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_chi_tiet_hoi_doan_giao_xu_id_ma_chi_tiet_hoi_doan_cu");

                    b.ToTable("chi_tiet_hoi_doan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChiTietLopGiaoLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChuGLy")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu_g_ly");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("boolean")
                        .HasColumnName("hoan_thanh");

                    b.Property<Guid>("LopGiaoLyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_giao_ly_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("SoThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("so_thu_tu");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chi_tiet_lop_giao_ly");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_chi_tiet_lop_giao_ly_giao_dan_id");

                    b.HasIndex("LopGiaoLyId")
                        .HasDatabaseName("ix_chi_tiet_lop_giao_ly_lop_giao_ly_id");

                    b.HasIndex("GiaoXuId", "LopGiaoLyId", "GiaoDanId")
                        .IsUnique()
                        .HasDatabaseName("ix_chi_tiet_lop_giao_ly_giao_xu_id_lop_giao_ly_id_giao_dan_id");

                    b.ToTable("chi_tiet_lop_giao_ly");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChuyenXu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChuChuyen")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu_chuyen");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("LoaiChuyen")
                        .HasColumnType("integer")
                        .HasColumnName("loai_chuyen");

                    b.Property<int>("MaChuyenXuCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_chuyen_xu_cu");

                    b.Property<DateOnly?>("NgayChuyen")
                        .HasColumnType("date")
                        .HasColumnName("ngay_chuyen");

                    b.Property<string>("NoiChuyen")
                        .HasColumnType("text")
                        .HasColumnName("noi_chuyen");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chuyen_xu");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_chuyen_xu_giao_dan_id");

                    b.HasIndex("GiaoXuId", "MaChuyenXuCu")
                        .IsUnique()
                        .HasDatabaseName("ix_chuyen_xu_giao_xu_id_ma_chuyen_xu_cu");

                    b.ToTable("chuyen_xu");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.DotBiTich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("LinhMuc")
                        .HasColumnType("text")
                        .HasColumnName("linh_muc");

                    b.Property<int>("LoaiBiTich")
                        .HasColumnType("integer")
                        .HasColumnName("loai_bi_tich");

                    b.Property<int>("MaDotBiTichCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_dot_bi_tich_cu");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateOnly?>("NgayBiTich")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bi_tich");

                    b.Property<string>("NoiBiTich")
                        .HasColumnType("text")
                        .HasColumnName("noi_bi_tich");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dot_bi_tich");

                    b.HasIndex("GiaoXuId", "MaDotBiTichCu")
                        .IsUnique()
                        .HasDatabaseName("ix_dot_bi_tich_giao_xu_id_ma_dot_bi_tich_cu");

                    b.ToTable("dot_bi_tich");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.DuLieuChung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieu1")
                        .HasColumnType("text")
                        .HasColumnName("du_lieu1");

                    b.Property<string>("DuLieu2")
                        .HasColumnType("text")
                        .HasColumnName("du_lieu2");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("LoaiDuLieu")
                        .HasColumnType("integer")
                        .HasColumnName("loai_du_lieu");

                    b.Property<string>("MaDuLieu")
                        .HasColumnType("text")
                        .HasColumnName("ma_du_lieu");

                    b.Property<int>("MaDuLieuChungCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_du_lieu_chung_cu");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_du_lieu_chung");

                    b.HasIndex("GiaoXuId", "LoaiDuLieu")
                        .HasDatabaseName("ix_du_lieu_chung_giao_xu_id_loai_du_lieu");

                    b.HasIndex("GiaoXuId", "MaDuLieuChungCu")
                        .IsUnique()
                        .HasDatabaseName("ix_du_lieu_chung_giao_xu_id_ma_du_lieu_chung_cu");

                    b.ToTable("du_lieu_chung");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaChuyenXu")
                        .HasColumnType("boolean")
                        .HasColumnName("da_chuyen_xu");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienGiaDinh")
                        .HasColumnType("text")
                        .HasColumnName("dien_gia_dinh");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiaoHoId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<bool>("KhongThongKe")
                        .HasColumnType("boolean")
                        .HasColumnName("khong_thong_ke");

                    b.Property<int>("MaGiaDinhCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_gia_dinh_cu");

                    b.Property<string>("MaGiaDinhRieng")
                        .HasColumnType("text")
                        .HasColumnName("ma_gia_dinh_rieng");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<DateOnly?>("NgayChuyen")
                        .HasColumnType("date")
                        .HasColumnName("ngay_chuyen");

                    b.Property<string>("NoiChuyen")
                        .HasColumnType("text")
                        .HasColumnName("noi_chuyen");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoHoKhau")
                        .HasColumnType("text")
                        .HasColumnName("so_ho_khau");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenGiaDinh")
                        .HasColumnType("text")
                        .HasColumnName("ten_gia_dinh");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gia_dinh");

                    b.HasIndex("GiaoHoId")
                        .HasDatabaseName("ix_gia_dinh_giao_ho_id");

                    b.HasIndex("GiaoXuId", "DaXoa")
                        .HasDatabaseName("ix_gia_dinh_giao_xu_id_da_xoa");

                    b.HasIndex("GiaoXuId", "MaGiaDinhCu")
                        .IsUnique()
                        .HasDatabaseName("ix_gia_dinh_giao_xu_id_ma_gia_dinh_cu");

                    b.ToTable("gia_dinh");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("BietNgoaiNgu")
                        .HasColumnType("text")
                        .HasColumnName("biet_ngoai_ngu");

                    b.Property<string>("CMND")
                        .HasColumnType("text")
                        .HasColumnName("cmnd");

                    b.Property<Guid?>("ChaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cha_id");

                    b.Property<string>("ChaRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("cha_rua_toi");

                    b.Property<string>("ChaRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("cha_ruoc_le");

                    b.Property<string>("ChaThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("cha_them_suc");

                    b.Property<bool>("ConHoc")
                        .HasColumnType("boolean")
                        .HasColumnName("con_hoc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaCoGiaDinh")
                        .HasColumnType("boolean")
                        .HasColumnName("da_co_gia_dinh");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DanToc")
                        .HasColumnType("text")
                        .HasColumnName("dan_toc");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("GhiChuXucDau")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu_xuc_dau");

                    b.Property<Guid?>("GiaoHoId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ho_ten");

                    b.Property<string>("HoTenCha")
                        .HasColumnType("text")
                        .HasColumnName("ho_ten_cha");

                    b.Property<string>("HoTenMe")
                        .HasColumnType("text")
                        .HasColumnName("ho_ten_me");

                    b.Property<bool>("KhongThongKe")
                        .HasColumnType("boolean")
                        .HasColumnName("khong_thong_ke");

                    b.Property<int>("MaGiaoDanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_dan_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<Guid?>("MeId")
                        .HasColumnType("uuid")
                        .HasColumnName("me_id");

                    b.Property<DateOnly?>("NgayBD1")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bd1");

                    b.Property<DateOnly?>("NgayBD2")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bd2");

                    b.Property<DateOnly?>("NgayGLHN1")
                        .HasColumnType("date")
                        .HasColumnName("ngay_glhn1");

                    b.Property<DateOnly?>("NgayGLHN2")
                        .HasColumnType("date")
                        .HasColumnName("ngay_glhn2");

                    b.Property<DateOnly?>("NgayQuaDoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_qua_doi");

                    b.Property<DateOnly?>("NgayRuaToi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_rua_toi");

                    b.Property<DateOnly?>("NgayRuocLe")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ruoc_le");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateOnly?>("NgayTHVaoDoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_th_vao_doi");

                    b.Property<DateOnly?>("NgayThemSuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_them_suc");

                    b.Property<DateOnly?>("NgayXucDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_xuc_dau");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text")
                        .HasColumnName("nghe_nghiep");

                    b.Property<string>("NguoiChungNhanGLHN")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung_nhan_glhn");

                    b.Property<string>("NguoiDoDauRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_do_dau_rua_toi");

                    b.Property<string>("NguoiDoDauThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_do_dau_them_suc");

                    b.Property<string>("NguoiXucDau")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_xuc_dau");

                    b.Property<string>("NoiAnTang")
                        .HasColumnType("text")
                        .HasColumnName("noi_an_tang");

                    b.Property<string>("NoiBD1")
                        .HasColumnType("text")
                        .HasColumnName("noi_bd1");

                    b.Property<string>("NoiBD2")
                        .HasColumnType("text")
                        .HasColumnName("noi_bd2");

                    b.Property<string>("NoiGLHN")
                        .HasColumnType("text")
                        .HasColumnName("noi_glhn");

                    b.Property<string>("NoiQuaDoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_qua_doi");

                    b.Property<string>("NoiRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("noi_rua_toi");

                    b.Property<string>("NoiRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("noi_ruoc_le");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("text")
                        .HasColumnName("noi_sinh");

                    b.Property<string>("NoiTHVaoDoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_th_vao_doi");

                    b.Property<string>("NoiThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("noi_them_suc");

                    b.Property<string>("Phai")
                        .HasColumnType("text")
                        .HasColumnName("phai");

                    b.Property<bool>("QuaDoi")
                        .HasColumnType("boolean")
                        .HasColumnName("qua_doi");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoAnTang")
                        .HasColumnType("text")
                        .HasColumnName("so_an_tang");

                    b.Property<string>("SoRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("so_rua_toi");

                    b.Property<string>("SoRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("so_ruoc_le");

                    b.Property<string>("SoThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("so_them_suc");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<bool>("TanTong")
                        .HasColumnType("boolean")
                        .HasColumnName("tan_tong");

                    b.Property<string>("TenThanh")
                        .HasColumnType("text")
                        .HasColumnName("ten_thanh");

                    b.Property<string>("ThuocGiaoPhan")
                        .HasColumnType("text")
                        .HasColumnName("thuoc_giao_phan");

                    b.Property<string>("ThuocGiaoXu")
                        .HasColumnType("text")
                        .HasColumnName("thuoc_giao_xu");

                    b.Property<string>("TinhTrangXucDau")
                        .HasColumnType("text")
                        .HasColumnName("tinh_trang_xuc_dau");

                    b.Property<string>("TrinhDoChuyenMon")
                        .HasColumnType("text")
                        .HasColumnName("trinh_do_chuyen_mon");

                    b.Property<string>("TrinhDoVanHoa")
                        .HasColumnType("text")
                        .HasColumnName("trinh_do_van_hoa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XepLoaiGLHN")
                        .HasColumnType("text")
                        .HasColumnName("xep_loai_glhn");

                    b.HasKey("Id")
                        .HasName("pk_giao_dan");

                    b.HasIndex("ChaId")
                        .HasDatabaseName("ix_giao_dan_cha_id");

                    b.HasIndex("GiaoHoId")
                        .HasDatabaseName("ix_giao_dan_giao_ho_id");

                    b.HasIndex("MeId")
                        .HasDatabaseName("ix_giao_dan_me_id");

                    b.HasIndex("GiaoXuId", "DaXoa")
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_da_xoa");

                    b.HasIndex("GiaoXuId", "HoTen")
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_ho_ten");

                    b.HasIndex("GiaoXuId", "MaGiaoDanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_ma_giao_dan_cu");

                    b.ToTable("giao_dan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDanHonPhoi", b =>
                {
                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("HonPhoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("hon_phoi_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("so_thu_tu");

                    b.HasKey("GiaoDanId", "HonPhoiId")
                        .HasName("pk_giao_dan_hon_phoi");

                    b.HasIndex("GiaoXuId")
                        .HasDatabaseName("ix_giao_dan_hon_phoi_giao_xu_id");

                    b.HasIndex("HonPhoiId")
                        .HasDatabaseName("ix_giao_dan_hon_phoi_hon_phoi_id");

                    b.ToTable("giao_dan_hon_phoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoPhanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_phan_id");

                    b.Property<int>("MaGiaoHatCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_hat_cu");

                    b.Property<int?>("MaGiaoHatRieng")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_hat_rieng");

                    b.Property<string>("TenGiaoHat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_hat");

                    b.HasKey("Id")
                        .HasName("pk_giao_hat");

                    b.HasIndex("GiaoPhanId")
                        .HasDatabaseName("ix_giao_hat_giao_phan_id");

                    b.HasIndex("MaGiaoHatCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_hat_ma_giao_hat_cu");

                    b.ToTable("giao_hat");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid?>("GiaoHoChaId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_cha_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaGiaoHoCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_ho_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenGiaoHo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_ho");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_giao_ho");

                    b.HasIndex("GiaoHoChaId")
                        .HasDatabaseName("ix_giao_ho_giao_ho_cha_id");

                    b.HasIndex("GiaoXuId", "MaGiaoHoCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_ho_giao_xu_id_ma_giao_ho_cu");

                    b.ToTable("giao_ho");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoLyVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<Guid>("LopGiaoLyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lop_giao_ly_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_giao_ly_vien");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_giao_ly_vien_giao_dan_id");

                    b.HasIndex("LopGiaoLyId")
                        .HasDatabaseName("ix_giao_ly_vien_lop_giao_ly_id");

                    b.HasIndex("GiaoXuId", "LopGiaoLyId", "GiaoDanId")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_ly_vien_giao_xu_id_lop_giao_ly_id_giao_dan_id");

                    b.ToTable("giao_ly_vien");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaGiaoPhanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_phan_cu");

                    b.Property<int?>("MaGiaoPhanRieng")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_phan_rieng");

                    b.Property<string>("TenGiaoPhan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_phan");

                    b.HasKey("Id")
                        .HasName("pk_giao_phan");

                    b.HasIndex("MaGiaoPhanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_phan_ma_giao_phan_cu");

                    b.ToTable("giao_phan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoXu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiaoHatId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_hat_id");

                    b.Property<string>("Hinh")
                        .HasColumnType("text")
                        .HasColumnName("hinh");

                    b.Property<DateTimeOffset?>("LastUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_upload");

                    b.Property<int?>("MaGiaoHatCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_hat_cu");

                    b.Property<int>("MaGiaoXuCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_xu_cu");

                    b.Property<int?>("MaGiaoXuRieng")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_xu_rieng");

                    b.Property<string>("TenGiaoXu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_xu");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_giao_xu");

                    b.HasIndex("GiaoHatId")
                        .HasDatabaseName("ix_giao_xu_giao_hat_id");

                    b.ToTable("giao_xu");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.HoiDoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaHoiDoanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_hoi_doan_cu");

                    b.Property<DateOnly?>("NgayBonMang")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bon_mang");

                    b.Property<DateOnly?>("NgayThanhLap")
                        .HasColumnType("date")
                        .HasColumnName("ngay_thanh_lap");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenHoiDoan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_hoi_doan");

                    b.Property<string>("ThanhBonMang")
                        .HasColumnType("text")
                        .HasColumnName("thanh_bon_mang");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hoi_doan");

                    b.HasIndex("GiaoXuId", "MaHoiDoanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_hoi_doan_giao_xu_id_ma_hoi_doan_cu");

                    b.ToTable("hoi_doan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.HonPhoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CachThucHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("cach_thuc_hon_phoi");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("LinhMucChung")
                        .HasColumnType("text")
                        .HasColumnName("linh_muc_chung");

                    b.Property<int>("MaHonPhoiCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_hon_phoi_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<DateOnly?>("NgayHonPhoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hon_phoi");

                    b.Property<string>("NguoiChung1")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung1");

                    b.Property<string>("NguoiChung2")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung2");

                    b.Property<string>("NoiHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_hon_phoi");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("so_hon_phoi");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("ten_hon_phoi");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hon_phoi");

                    b.HasIndex("GiaoXuId")
                        .HasDatabaseName("ix_hon_phoi_giao_xu_id");

                    b.HasIndex("GiaoXuId", "MaHonPhoiCu")
                        .IsUnique()
                        .HasDatabaseName("ix_hon_phoi_giao_xu_id_ma_hon_phoi_cu");

                    b.ToTable("hon_phoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.KhoiGiaoLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaKhoiCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_khoi_cu");

                    b.Property<Guid?>("NguoiQuanLyId")
                        .HasColumnType("uuid")
                        .HasColumnName("nguoi_quan_ly_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenKhoi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_khoi");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_khoi_giao_ly");

                    b.HasIndex("NguoiQuanLyId")
                        .HasDatabaseName("ix_khoi_giao_ly_nguoi_quan_ly_id");

                    b.HasIndex("GiaoXuId", "MaKhoiCu")
                        .IsUnique()
                        .HasDatabaseName("ix_khoi_giao_ly_giao_xu_id_ma_khoi_cu");

                    b.ToTable("khoi_giao_ly");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.LinhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChucVu")
                        .HasColumnType("text")
                        .HasColumnName("chuc_vu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<DateOnly?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("den_ngay");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ho_ten");

                    b.Property<int>("MaLinhMucCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_linh_muc_cu");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenThanh")
                        .HasColumnType("text")
                        .HasColumnName("ten_thanh");

                    b.Property<DateOnly?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("tu_ngay");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_linh_muc");

                    b.HasIndex("GiaoXuId", "MaLinhMucCu")
                        .IsUnique()
                        .HasDatabaseName("ix_linh_muc_giao_xu_id_ma_linh_muc_cu");

                    b.ToTable("linh_muc");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.LopGiaoLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<Guid>("KhoiGiaoLyId")
                        .HasColumnType("uuid")
                        .HasColumnName("khoi_giao_ly_id");

                    b.Property<int>("MaLopCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_lop_cu");

                    b.Property<int?>("Nam")
                        .HasColumnType("integer")
                        .HasColumnName("nam");

                    b.Property<string>("PhongHoc")
                        .HasColumnType("text")
                        .HasColumnName("phong_hoc");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_lop");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lop_giao_ly");

                    b.HasIndex("KhoiGiaoLyId")
                        .HasDatabaseName("ix_lop_giao_ly_khoi_giao_ly_id");

                    b.HasIndex("GiaoXuId", "MaLopCu")
                        .IsUnique()
                        .HasDatabaseName("ix_lop_giao_ly_giao_xu_id_ma_lop_cu");

                    b.ToTable("lop_giao_ly");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.RaoHonPhoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiaoDan1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan1_id");

                    b.Property<Guid?>("GiaoDan2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan2_id");

                    b.Property<string>("GiaoPhan1")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan1");

                    b.Property<string>("GiaoPhan2")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan2");

                    b.Property<string>("GiaoPhanNQ1")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan_nq1");

                    b.Property<string>("GiaoPhanNQ2")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan_nq2");

                    b.Property<string>("GiaoPhanTruoc1")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan_truoc1");

                    b.Property<string>("GiaoPhanTruoc2")
                        .HasColumnType("text")
                        .HasColumnName("giao_phan_truoc2");

                    b.Property<string>("GiaoXu1")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu1");

                    b.Property<string>("GiaoXu2")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu2");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("GiaoXuNQ1")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu_nq1");

                    b.Property<string>("GiaoXuNQ2")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu_nq2");

                    b.Property<string>("GiaoXuNhan")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu_nhan");

                    b.Property<string>("GiaoXuTruoc1")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu_truoc1");

                    b.Property<string>("GiaoXuTruoc2")
                        .HasColumnType("text")
                        .HasColumnName("giao_xu_truoc2");

                    b.Property<string>("LinhMucNhan")
                        .HasColumnType("text")
                        .HasColumnName("linh_muc_nhan");

                    b.Property<int>("MaRaoHonPhoiCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_rao_hon_phoi_cu");

                    b.Property<DateOnly?>("NgayRaoLan1")
                        .HasColumnType("date")
                        .HasColumnName("ngay_rao_lan1");

                    b.Property<DateOnly?>("NgayRaoLan2")
                        .HasColumnType("date")
                        .HasColumnName("ngay_rao_lan2");

                    b.Property<DateOnly?>("NgayRaoLan3")
                        .HasColumnType("date")
                        .HasColumnName("ngay_rao_lan3");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Tam1")
                        .HasColumnType("text")
                        .HasColumnName("tam1");

                    b.Property<string>("Tam2")
                        .HasColumnType("text")
                        .HasColumnName("tam2");

                    b.Property<string>("Tam3")
                        .HasColumnType("text")
                        .HasColumnName("tam3");

                    b.Property<string>("TenRaoHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("ten_rao_hon_phoi");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rao_hon_phoi");

                    b.HasIndex("GiaoDan1Id")
                        .HasDatabaseName("ix_rao_hon_phoi_giao_dan1_id");

                    b.HasIndex("GiaoDan2Id")
                        .HasDatabaseName("ix_rao_hon_phoi_giao_dan2_id");

                    b.HasIndex("GiaoXuId", "MaRaoHonPhoiCu")
                        .IsUnique()
                        .HasDatabaseName("ix_rao_hon_phoi_giao_xu_id_ma_rao_hon_phoi_cu");

                    b.ToTable("rao_hon_phoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CauHoiGoiY")
                        .HasColumnType("text")
                        .HasColumnName("cau_hoi_goi_y");

                    b.Property<string>("CauTraLoiGoiY")
                        .HasColumnType("text")
                        .HasColumnName("cau_tra_loi_goi_y");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("HoTenNguoiDung")
                        .HasColumnType("text")
                        .HasColumnName("ho_ten_nguoi_dung");

                    b.Property<int>("LoaiTaiKhoan")
                        .HasColumnType("integer")
                        .HasColumnName("loai_tai_khoan");

                    b.Property<string>("MatKhauBam")
                        .HasColumnType("text")
                        .HasColumnName("mat_khau_bam");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_tai_khoan");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tai_khoan");

                    b.HasIndex("GiaoXuId", "TenTaiKhoan")
                        .IsUnique()
                        .HasDatabaseName("ix_tai_khoan_giao_xu_id_ten_tai_khoan");

                    b.ToTable("tai_khoan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.TanHien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChucVu")
                        .HasColumnType("text")
                        .HasColumnName("chuc_vu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaHoiTuc")
                        .HasColumnType("boolean")
                        .HasColumnName("da_hoi_tuc");

                    b.Property<string>("DiaChiPhucVu")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi_phuc_vu");

                    b.Property<string>("DienThoaiPhucVu")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai_phuc_vu");

                    b.Property<string>("DongTu")
                        .HasColumnType("text")
                        .HasColumnName("dong_tu");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("EmailPhucVu")
                        .HasColumnType("text")
                        .HasColumnName("email_phuc_vu");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaTanHienCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_tan_hien_cu");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayBonMang")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bon_mang");

                    b.Property<DateOnly?>("NgayPhoTe")
                        .HasColumnType("date")
                        .HasColumnName("ngay_pho_te");

                    b.Property<DateOnly?>("NgayThuPhongLM")
                        .HasColumnType("date")
                        .HasColumnName("ngay_thu_phong_lm");

                    b.Property<DateOnly?>("NgayVaoDCV")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_dcv");

                    b.Property<DateOnly?>("NgayVaoKhanLanDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_khan_lan_dau");

                    b.Property<DateOnly?>("NgayVaoKhanTronDoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_khan_tron_doi");

                    b.Property<DateOnly?>("NgayVaoNhaTap")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_nha_tap");

                    b.Property<DateOnly?>("NgayVaoNhaThu")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_nha_thu");

                    b.Property<string>("NoiPhucVu")
                        .HasColumnType("text")
                        .HasColumnName("noi_phuc_vu");

                    b.Property<string>("NoiTu")
                        .HasColumnType("text")
                        .HasColumnName("noi_tu");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tan_hien");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_tan_hien_giao_dan_id");

                    b.HasIndex("GiaoXuId", "MaTanHienCu")
                        .IsUnique()
                        .HasDatabaseName("ix_tan_hien_giao_xu_id_ma_tan_hien_cu");

                    b.ToTable("tan_hien");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.TenLoaiTaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaLoaiTaiKhoanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_loai_tai_khoan_cu");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenLoai")
                        .HasColumnType("text")
                        .HasColumnName("ten_loai");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ten_loai_tai_khoan");

                    b.HasIndex("GiaoXuId", "MaLoaiTaiKhoanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_ten_loai_tai_khoan_giao_xu_id_ma_loai_tai_khoan_cu");

                    b.ToTable("ten_loai_tai_khoan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ThanhVienGiaDinh", b =>
                {
                    b.Property<Guid>("GiaDinhId")
                        .HasColumnType("uuid")
                        .HasColumnName("gia_dinh_id");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<int>("VaiTro")
                        .HasColumnType("integer")
                        .HasColumnName("vai_tro");

                    b.Property<bool>("ChuHo")
                        .HasColumnType("boolean")
                        .HasColumnName("chu_ho");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.HasKey("GiaDinhId", "GiaoDanId", "VaiTro")
                        .HasName("pk_thanh_vien_gia_dinh");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_thanh_vien_gia_dinh_giao_dan_id");

                    b.HasIndex("GiaDinhId", "VaiTro")
                        .IsUnique()
                        .HasDatabaseName("ux_thanh_vien_gia_dinh_mot_chong_mot_vo")
                        .HasFilter("vai_tro IN (0, 1)");

                    b.HasIndex("GiaoXuId", "GiaDinhId")
                        .HasDatabaseName("ix_thanh_vien_gia_dinh_giao_xu_id_gia_dinh_id");

                    b.ToTable("thanh_vien_gia_dinh");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaVaiTroCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_vai_tro_cu");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_vai_tro");

                    b.HasIndex("GiaoXuId", "MaVaiTroCu")
                        .IsUnique()
                        .HasDatabaseName("ix_vai_tro_giao_xu_id_ma_vai_tro_cu");

                    b.ToTable("vai_tro");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.BiTichChiTiet", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.DotBiTich", "DotBiTich")
                        .WithMany("ChiTiet")
                        .HasForeignKey("DotBiTichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bi_tich_chi_tiet__dot_bi_tich_dot_bi_tich_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bi_tich_chi_tiet__giao_dan_giao_dan_id");

                    b.Navigation("DotBiTich");

                    b.Navigation("GiaoDan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChiTietHoiDoan", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_hoi_doan__giao_dan_giao_dan_id");

                    b.HasOne("Qlgx.Domain.Entities.HoiDoan", "HoiDoan")
                        .WithMany()
                        .HasForeignKey("HoiDoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_hoi_doan__hoi_doan_hoi_doan_id");

                    b.Navigation("GiaoDan");

                    b.Navigation("HoiDoan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChiTietLopGiaoLy", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_lop_giao_ly__giao_dan_giao_dan_id");

                    b.HasOne("Qlgx.Domain.Entities.LopGiaoLy", "LopGiaoLy")
                        .WithMany()
                        .HasForeignKey("LopGiaoLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chi_tiet_lop_giao_ly__lop_giao_ly_lop_giao_ly_id");

                    b.Navigation("GiaoDan");

                    b.Navigation("LopGiaoLy");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ChuyenXu", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chuyen_xu__giao_dan_giao_dan_id");

                    b.Navigation("GiaoDan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", "GiaoHo")
                        .WithMany()
                        .HasForeignKey("GiaoHoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gia_dinh__giao_ho_giao_ho_id");

                    b.Navigation("GiaoHo");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", null)
                        .WithMany()
                        .HasForeignKey("ChaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_giao_dan_giao_dan_cha_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", "GiaoHo")
                        .WithMany()
                        .HasForeignKey("GiaoHoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_giao_dan__giao_ho_giao_ho_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", null)
                        .WithMany()
                        .HasForeignKey("MeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_giao_dan_giao_dan_me_id");

                    b.Navigation("GiaoHo");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDanHonPhoi", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giao_dan_hon_phoi_giao_dan_giao_dan_id");

                    b.HasOne("Qlgx.Domain.Entities.HonPhoi", "HonPhoi")
                        .WithMany("GiaoDanThamGia")
                        .HasForeignKey("HonPhoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giao_dan_hon_phoi__hon_phoi_hon_phoi_id");

                    b.Navigation("GiaoDan");

                    b.Navigation("HonPhoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHat", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoPhan", "GiaoPhan")
                        .WithMany()
                        .HasForeignKey("GiaoPhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_giao_hat__giao_phan_giao_phan_id");

                    b.Navigation("GiaoPhan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHo", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", null)
                        .WithMany()
                        .HasForeignKey("GiaoHoChaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_giao_ho_giao_ho_giao_ho_cha_id");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoLyVien", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_giao_ly_vien_giao_dan_giao_dan_id");

                    b.HasOne("Qlgx.Domain.Entities.LopGiaoLy", "LopGiaoLy")
                        .WithMany()
                        .HasForeignKey("LopGiaoLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giao_ly_vien__lop_giao_ly_lop_giao_ly_id");

                    b.Navigation("GiaoDan");

                    b.Navigation("LopGiaoLy");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoXu", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHat", "GiaoHat")
                        .WithMany()
                        .HasForeignKey("GiaoHatId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_giao_xu_giao_hat_giao_hat_id");

                    b.Navigation("GiaoHat");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.KhoiGiaoLy", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "NguoiQuanLy")
                        .WithMany()
                        .HasForeignKey("NguoiQuanLyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_khoi_giao_ly_giao_dan_nguoi_quan_ly_id");

                    b.Navigation("NguoiQuanLy");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.LopGiaoLy", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.KhoiGiaoLy", "KhoiGiaoLy")
                        .WithMany()
                        .HasForeignKey("KhoiGiaoLyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lop_giao_ly_khoi_giao_ly_khoi_giao_ly_id");

                    b.Navigation("KhoiGiaoLy");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.RaoHonPhoi", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan1")
                        .WithMany()
                        .HasForeignKey("GiaoDan1Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rao_hon_phoi_giao_dan_giao_dan1_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan2")
                        .WithMany()
                        .HasForeignKey("GiaoDan2Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rao_hon_phoi_giao_dan_giao_dan2_id");

                    b.Navigation("GiaoDan1");

                    b.Navigation("GiaoDan2");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.TanHien", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tan_hien_giao_dan_giao_dan_id");

                    b.Navigation("GiaoDan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ThanhVienGiaDinh", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaDinh", "GiaDinh")
                        .WithMany("ThanhVien")
                        .HasForeignKey("GiaDinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_vien_gia_dinh_gia_dinh_gia_dinh_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany("GiaDinhThamGia")
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_vien_gia_dinh_giao_dan_giao_dan_id");

                    b.Navigation("GiaDinh");

                    b.Navigation("GiaoDan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.DotBiTich", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.Navigation("GiaDinhThamGia");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.HonPhoi", b =>
                {
                    b.Navigation("GiaoDanThamGia");
                });
#pragma warning restore 612, 618
        }
    }
}
