// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qlgx.Data;

#nullable disable

namespace Qlgx.Data.Migrations
{
    [DbContext(typeof(QlgxDbContext))]
    [Migration("20260906045200_SchemaBanDau")]
    partial class SchemaBanDau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaChuyenXu")
                        .HasColumnType("boolean")
                        .HasColumnName("da_chuyen_xu");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienGiaDinh")
                        .HasColumnType("text")
                        .HasColumnName("dien_gia_dinh");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiaoHoId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<bool>("KhongThongKe")
                        .HasColumnType("boolean")
                        .HasColumnName("khong_thong_ke");

                    b.Property<int>("MaGiaDinhCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_gia_dinh_cu");

                    b.Property<string>("MaGiaDinhRieng")
                        .HasColumnType("text")
                        .HasColumnName("ma_gia_dinh_rieng");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<DateOnly?>("NgayChuyen")
                        .HasColumnType("date")
                        .HasColumnName("ngay_chuyen");

                    b.Property<string>("NoiChuyen")
                        .HasColumnType("text")
                        .HasColumnName("noi_chuyen");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoHoKhau")
                        .HasColumnType("text")
                        .HasColumnName("so_ho_khau");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenGiaDinh")
                        .HasColumnType("text")
                        .HasColumnName("ten_gia_dinh");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gia_dinh");

                    b.HasIndex("GiaoHoId")
                        .HasDatabaseName("ix_gia_dinh_giao_ho_id");

                    b.HasIndex("GiaoXuId", "DaXoa")
                        .HasDatabaseName("ix_gia_dinh_giao_xu_id_da_xoa");

                    b.HasIndex("GiaoXuId", "MaGiaDinhCu")
                        .IsUnique()
                        .HasDatabaseName("ix_gia_dinh_giao_xu_id_ma_gia_dinh_cu");

                    b.ToTable("gia_dinh");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("BietNgoaiNgu")
                        .HasColumnType("text")
                        .HasColumnName("biet_ngoai_ngu");

                    b.Property<string>("CMND")
                        .HasColumnType("text")
                        .HasColumnName("cmnd");

                    b.Property<string>("ChaRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("cha_rua_toi");

                    b.Property<string>("ChaRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("cha_ruoc_le");

                    b.Property<string>("ChaThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("cha_them_suc");

                    b.Property<bool>("ConHoc")
                        .HasColumnType("boolean")
                        .HasColumnName("con_hoc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaCoGiaDinh")
                        .HasColumnType("boolean")
                        .HasColumnName("da_co_gia_dinh");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DanToc")
                        .HasColumnType("text")
                        .HasColumnName("dan_toc");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("GhiChuXucDau")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu_xuc_dau");

                    b.Property<Guid?>("GiaoHoId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ho_ten");

                    b.Property<string>("HoTenCha")
                        .HasColumnType("text")
                        .HasColumnName("ho_ten_cha");

                    b.Property<string>("HoTenMe")
                        .HasColumnType("text")
                        .HasColumnName("ho_ten_me");

                    b.Property<bool>("KhongThongKe")
                        .HasColumnType("boolean")
                        .HasColumnName("khong_thong_ke");

                    b.Property<int>("MaGiaoDanCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_dan_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<DateOnly?>("NgayBD1")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bd1");

                    b.Property<DateOnly?>("NgayBD2")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bd2");

                    b.Property<DateOnly?>("NgayGLHN1")
                        .HasColumnType("date")
                        .HasColumnName("ngay_glhn1");

                    b.Property<DateOnly?>("NgayGLHN2")
                        .HasColumnType("date")
                        .HasColumnName("ngay_glhn2");

                    b.Property<DateOnly?>("NgayQuaDoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_qua_doi");

                    b.Property<DateOnly?>("NgayRuaToi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_rua_toi");

                    b.Property<DateOnly?>("NgayRuocLe")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ruoc_le");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateOnly?>("NgayTHVaoDoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_th_vao_doi");

                    b.Property<DateOnly?>("NgayThemSuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_them_suc");

                    b.Property<DateOnly?>("NgayXucDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_xuc_dau");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text")
                        .HasColumnName("nghe_nghiep");

                    b.Property<string>("NguoiChungNhanGLHN")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung_nhan_glhn");

                    b.Property<string>("NguoiDoDauRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_do_dau_rua_toi");

                    b.Property<string>("NguoiDoDauThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_do_dau_them_suc");

                    b.Property<string>("NguoiXucDau")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_xuc_dau");

                    b.Property<string>("NoiAnTang")
                        .HasColumnType("text")
                        .HasColumnName("noi_an_tang");

                    b.Property<string>("NoiBD1")
                        .HasColumnType("text")
                        .HasColumnName("noi_bd1");

                    b.Property<string>("NoiBD2")
                        .HasColumnType("text")
                        .HasColumnName("noi_bd2");

                    b.Property<string>("NoiGLHN")
                        .HasColumnType("text")
                        .HasColumnName("noi_glhn");

                    b.Property<string>("NoiQuaDoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_qua_doi");

                    b.Property<string>("NoiRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("noi_rua_toi");

                    b.Property<string>("NoiRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("noi_ruoc_le");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("text")
                        .HasColumnName("noi_sinh");

                    b.Property<string>("NoiTHVaoDoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_th_vao_doi");

                    b.Property<string>("NoiThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("noi_them_suc");

                    b.Property<string>("Phai")
                        .HasColumnType("text")
                        .HasColumnName("phai");

                    b.Property<bool>("QuaDoi")
                        .HasColumnType("boolean")
                        .HasColumnName("qua_doi");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoAnTang")
                        .HasColumnType("text")
                        .HasColumnName("so_an_tang");

                    b.Property<string>("SoRuaToi")
                        .HasColumnType("text")
                        .HasColumnName("so_rua_toi");

                    b.Property<string>("SoRuocLe")
                        .HasColumnType("text")
                        .HasColumnName("so_ruoc_le");

                    b.Property<string>("SoThemSuc")
                        .HasColumnType("text")
                        .HasColumnName("so_them_suc");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<bool>("TanTong")
                        .HasColumnType("boolean")
                        .HasColumnName("tan_tong");

                    b.Property<string>("TenThanh")
                        .HasColumnType("text")
                        .HasColumnName("ten_thanh");

                    b.Property<string>("ThuocGiaoPhan")
                        .HasColumnType("text")
                        .HasColumnName("thuoc_giao_phan");

                    b.Property<string>("ThuocGiaoXu")
                        .HasColumnType("text")
                        .HasColumnName("thuoc_giao_xu");

                    b.Property<string>("TinhTrangXucDau")
                        .HasColumnType("text")
                        .HasColumnName("tinh_trang_xuc_dau");

                    b.Property<string>("TrinhDoChuyenMon")
                        .HasColumnType("text")
                        .HasColumnName("trinh_do_chuyen_mon");

                    b.Property<string>("TrinhDoVanHoa")
                        .HasColumnType("text")
                        .HasColumnName("trinh_do_van_hoa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XepLoaiGLHN")
                        .HasColumnType("text")
                        .HasColumnName("xep_loai_glhn");

                    b.HasKey("Id")
                        .HasName("pk_giao_dan");

                    b.HasIndex("GiaoHoId")
                        .HasDatabaseName("ix_giao_dan_giao_ho_id");

                    b.HasIndex("GiaoXuId", "DaXoa")
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_da_xoa");

                    b.HasIndex("GiaoXuId", "HoTen")
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_ho_ten");

                    b.HasIndex("GiaoXuId", "MaGiaoDanCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_dan_giao_xu_id_ma_giao_dan_cu");

                    b.ToTable("giao_dan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDanHonPhoi", b =>
                {
                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<Guid>("HonPhoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("hon_phoi_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("integer")
                        .HasColumnName("so_thu_tu");

                    b.HasKey("GiaoDanId", "HonPhoiId")
                        .HasName("pk_giao_dan_hon_phoi");

                    b.HasIndex("GiaoXuId")
                        .HasDatabaseName("ix_giao_dan_hon_phoi_giao_xu_id");

                    b.HasIndex("HonPhoiId")
                        .HasDatabaseName("ix_giao_dan_hon_phoi_hon_phoi_id");

                    b.ToTable("giao_dan_hon_phoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean")
                        .HasColumnName("da_xoa");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<Guid?>("GiaoHoChaId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_ho_cha_id");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<int>("MaGiaoHoCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_ho_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenGiaoHo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_ho");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_giao_ho");

                    b.HasIndex("GiaoHoChaId")
                        .HasDatabaseName("ix_giao_ho_giao_ho_cha_id");

                    b.HasIndex("GiaoXuId", "MaGiaoHoCu")
                        .IsUnique()
                        .HasDatabaseName("ix_giao_ho_giao_xu_id_ma_giao_ho_cu");

                    b.ToTable("giao_ho");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoXu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text")
                        .HasColumnName("dia_chi");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text")
                        .HasColumnName("dien_thoai");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaGiaoXuCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_xu_cu");

                    b.Property<int?>("MaGiaoXuRieng")
                        .HasColumnType("integer")
                        .HasColumnName("ma_giao_xu_rieng");

                    b.Property<string>("TenGiaoHat")
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_hat");

                    b.Property<string>("TenGiaoPhan")
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_phan");

                    b.Property<string>("TenGiaoXu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ten_giao_xu");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_giao_xu");

                    b.ToTable("giao_xu");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.HonPhoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CachThucHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("cach_thuc_hon_phoi");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DuLieuLoi")
                        .HasColumnType("jsonb")
                        .HasColumnName("du_lieu_loi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.Property<string>("LinhMucChung")
                        .HasColumnType("text")
                        .HasColumnName("linh_muc_chung");

                    b.Property<int>("MaHonPhoiCu")
                        .HasColumnType("integer")
                        .HasColumnName("ma_hon_phoi_cu");

                    b.Property<string>("MaNhanDang")
                        .HasColumnType("text")
                        .HasColumnName("ma_nhan_dang");

                    b.Property<DateOnly?>("NgayHonPhoi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hon_phoi");

                    b.Property<string>("NguoiChung1")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung1");

                    b.Property<string>("NguoiChung2")
                        .HasColumnType("text")
                        .HasColumnName("nguoi_chung2");

                    b.Property<string>("NoiHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("noi_hon_phoi");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SoHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("so_hon_phoi");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TenHonPhoi")
                        .HasColumnType("text")
                        .HasColumnName("ten_hon_phoi");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hon_phoi");

                    b.HasIndex("GiaoXuId")
                        .HasDatabaseName("ix_hon_phoi_giao_xu_id");

                    b.HasIndex("GiaoXuId", "MaHonPhoiCu")
                        .IsUnique()
                        .HasDatabaseName("ix_hon_phoi_giao_xu_id_ma_hon_phoi_cu");

                    b.ToTable("hon_phoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ThanhVienGiaDinh", b =>
                {
                    b.Property<Guid>("GiaDinhId")
                        .HasColumnType("uuid")
                        .HasColumnName("gia_dinh_id");

                    b.Property<Guid>("GiaoDanId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_dan_id");

                    b.Property<int>("VaiTro")
                        .HasColumnType("integer")
                        .HasColumnName("vai_tro");

                    b.Property<bool>("ChuHo")
                        .HasColumnType("boolean")
                        .HasColumnName("chu_ho");

                    b.Property<Guid>("GiaoXuId")
                        .HasColumnType("uuid")
                        .HasColumnName("giao_xu_id");

                    b.HasKey("GiaDinhId", "GiaoDanId", "VaiTro")
                        .HasName("pk_thanh_vien_gia_dinh");

                    b.HasIndex("GiaoDanId")
                        .HasDatabaseName("ix_thanh_vien_gia_dinh_giao_dan_id");

                    b.HasIndex("GiaoXuId", "GiaDinhId")
                        .HasDatabaseName("ix_thanh_vien_gia_dinh_giao_xu_id_gia_dinh_id");

                    b.ToTable("thanh_vien_gia_dinh");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", "GiaoHo")
                        .WithMany()
                        .HasForeignKey("GiaoHoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gia_dinh__giao_ho_giao_ho_id");

                    b.Navigation("GiaoHo");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", "GiaoHo")
                        .WithMany()
                        .HasForeignKey("GiaoHoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_giao_dan__giao_ho_giao_ho_id");

                    b.Navigation("GiaoHo");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDanHonPhoi", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany()
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giao_dan_hon_phoi_giao_dan_giao_dan_id");

                    b.HasOne("Qlgx.Domain.Entities.HonPhoi", "HonPhoi")
                        .WithMany("GiaoDanThamGia")
                        .HasForeignKey("HonPhoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giao_dan_hon_phoi__hon_phoi_hon_phoi_id");

                    b.Navigation("GiaoDan");

                    b.Navigation("HonPhoi");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoHo", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaoHo", null)
                        .WithMany()
                        .HasForeignKey("GiaoHoChaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_giao_ho_giao_ho_giao_ho_cha_id");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.ThanhVienGiaDinh", b =>
                {
                    b.HasOne("Qlgx.Domain.Entities.GiaDinh", "GiaDinh")
                        .WithMany("ThanhVien")
                        .HasForeignKey("GiaDinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_vien_gia_dinh_gia_dinh_gia_dinh_id");

                    b.HasOne("Qlgx.Domain.Entities.GiaoDan", "GiaoDan")
                        .WithMany("GiaDinhThamGia")
                        .HasForeignKey("GiaoDanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_vien_gia_dinh_giao_dan_giao_dan_id");

                    b.Navigation("GiaDinh");

                    b.Navigation("GiaoDan");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaDinh", b =>
                {
                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.GiaoDan", b =>
                {
                    b.Navigation("GiaDinhThamGia");
                });

            modelBuilder.Entity("Qlgx.Domain.Entities.HonPhoi", b =>
                {
                    b.Navigation("GiaoDanThamGia");
                });
#pragma warning restore 612, 618
        }
    }
}
