#!/usr/bin/env bats
# I2 (review backend) -- ba bang sao luu KHONG duoc de vai tro ung dung lam chu.
#
# cong_viec_sao_luu la mot HANG DOI MA LENH, va thu thi hanh no (qlgx-runner.sh) chay duoi quyen
# ROOT tren host. EF Core migration tao ba bang nay va migration chay bang qlgx_app, nen theo mac
# dinh cua Postgres ca ba thuoc ve vai tro IT TIN CAY NHAT -- tuc mot duong leo thang dac quyen
# neu vai tro ung dung bi chiem qua web. Thiet ke muc 7.4: ba bang "chi truy cap duoc qua vai tro
# qlgx_admin".
#
# Chay THAT tren mot PostgreSQL that: day la loai thuoc tinh chi co CSDL that moi tra loi duoc.

can_docker() { command -v docker >/dev/null 2>&1 || skip "can lenh docker (chay bo test nay tren host)"; }

setup_file() {
  command -v docker >/dev/null 2>&1 || return 0
  export TEN_CT="qlgx-thu-quyen-$$"
  docker run -d --name "$TEN_CT" -e POSTGRES_PASSWORD=thu_nghiem_tam \
    -e POSTGRES_DB=qlgx postgres:17-alpine >/dev/null
  for _ in $(seq 1 30); do
    docker exec "$TEN_CT" pg_isready -U postgres -d qlgx >/dev/null 2>&1 && break
    sleep 1
  done
}

teardown_file() { command -v docker >/dev/null 2>&1 && docker rm -f "${TEN_CT:-}" >/dev/null 2>&1 || true; }

hoi() { docker exec "$TEN_CT" psql -tAX -U postgres -d qlgx -c "$1" | tr -d ' \r'; }

# Chay 00-vai-tro-rls.sql (tao hai vai tro) roi 01-bang-sao-luu-quyen.sql (siet quyen).
chay_vai_tro() {
  docker exec -i "$TEN_CT" psql -v ON_ERROR_STOP=1 -U postgres -d qlgx \
    -v qlgx_app_user=qlgx_app -v qlgx_app_password=mk_app \
    -v qlgx_admin_user=qlgx_admin -v qlgx_admin_password=mk_admin \
    -f - < "${BATS_TEST_DIRNAME}/../../scripts/sql/00-vai-tro-rls.sql"
}
chay_siet_quyen() {
  {
    printf "SELECT set_config('qlgx.app_user', 'qlgx_app', false);\n"
    printf "SELECT set_config('qlgx.admin_user', 'qlgx_admin', false);\n"
    cat "${BATS_TEST_DIRNAME}/../../scripts/sql/01-bang-sao-luu-quyen.sql"
  } | docker exec -i "$TEN_CT" psql -v ON_ERROR_STOP=1 -U postgres -d qlgx
}

# Mo phong dung kich ban san xuat: ba bang do CHINH qlgx_app tao ra (migration EF chay bang vai
# tro do), nen mac dinh qlgx_app la CHU. Neu test tao bang bang "postgres" thi phep thu se dat
# ngay ca khi ban sua khong lam gi -- mot phep thu gia.
tao_ba_bang_bang_qlgx_app() {
  docker exec "$TEN_CT" psql -q -U qlgx_app -d qlgx -c \
    "CREATE TABLE IF NOT EXISTS cong_viec_sao_luu (id uuid PRIMARY KEY, loai text, trang_thai text);
     CREATE TABLE IF NOT EXISTS ban_sao_luu (id text PRIMARY KEY, nhan text);
     CREATE TABLE IF NOT EXISTS trang_thai_sao_luu (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, loi_gan_nhat text);"
}

@test "I2: sau khi siet quyen, chu ba bang la vai tro QUAN TRI (khong phai vai tro ung dung)" {
  can_docker
  chay_vai_tro
  tao_ba_bang_bang_qlgx_app
  # Doi chung: TRUOC khi siet, chu la qlgx_app -- chung to phep thu nay khong phai lam.
  [ "$(hoi "SELECT tableowner FROM pg_tables WHERE tablename='cong_viec_sao_luu'")" = "qlgx_app" ]
  run chay_siet_quyen
  [ "$status" -eq 0 ]
  [ "$(hoi "SELECT tableowner FROM pg_tables WHERE tablename='cong_viec_sao_luu'")" = "qlgx_admin" ]
  [ "$(hoi "SELECT tableowner FROM pg_tables WHERE tablename='ban_sao_luu'")" = "qlgx_admin" ]
  [ "$(hoi "SELECT tableowner FROM pg_tables WHERE tablename='trang_thai_sao_luu'")" = "qlgx_admin" ]
}

# Day moi la dieu THAT SU quan trong: vai tro ung dung KHONG duoc xep viec vao hang doi ma root
# thi hanh.
@test "I2: vai tro ung dung KHONG ghi duoc vao hang doi cong viec" {
  can_docker
  chay_vai_tro
  tao_ba_bang_bang_qlgx_app
  chay_siet_quyen
  run docker exec "$TEN_CT" psql -v ON_ERROR_STOP=1 -U qlgx_app -d qlgx -c \
    "INSERT INTO cong_viec_sao_luu (id, loai, trang_thai) VALUES (gen_random_uuid(), 'sao_luu', 'cho')"
  [ "$status" -ne 0 ]
  run docker exec "$TEN_CT" psql -v ON_ERROR_STOP=1 -U qlgx_app -d qlgx -c \
    "SELECT * FROM cong_viec_sao_luu"
  [ "$status" -ne 0 ]
}

@test "I2: vai tro QUAN TRI van ghi va doc duoc binh thuong (khong tu khoa chinh minh)" {
  can_docker
  chay_vai_tro
  tao_ba_bang_bang_qlgx_app
  chay_siet_quyen
  run docker exec "$TEN_CT" psql -v ON_ERROR_STOP=1 -U qlgx_admin -d qlgx -c \
    "INSERT INTO cong_viec_sao_luu (id, loai, trang_thai) VALUES (gen_random_uuid(), 'sao_luu', 'cho')"
  [ "$status" -eq 0 ]
  run docker exec "$TEN_CT" psql -v ON_ERROR_STOP=1 -U qlgx_admin -d qlgx -c \
    "INSERT INTO trang_thai_sao_luu (loi_gan_nhat) VALUES ('thu')"
  [ "$status" -eq 0 ]   # sequence cung phai da doi chu, neu khong se 'permission denied for sequence'
}

# Lan cai moi dau tien: install.sh chay SQL nay TRUOC khi migration kip tao bang. Khong duoc chet.
@test "I2: ba bang CHUA ton tai thi khong duoc bao loi (lan cai moi dau tien)" {
  can_docker
  docker exec "$TEN_CT" psql -q -U postgres -d qlgx -c \
    "DROP TABLE IF EXISTS cong_viec_sao_luu, ban_sao_luu, trang_thai_sao_luu" >/dev/null
  chay_vai_tro
  run chay_siet_quyen
  [ "$status" -eq 0 ]
}

@test "I2: chay lai lan hai khong loi (idempotent)" {
  can_docker
  chay_vai_tro
  tao_ba_bang_bang_qlgx_app
  chay_siet_quyen
  run chay_siet_quyen
  [ "$status" -eq 0 ]
  [ "$(hoi "SELECT tableowner FROM pg_tables WHERE tablename='ban_sao_luu'")" = "qlgx_admin" ]
}

@test "I2: tu choi khi hai ten vai tro trung nhau (RLS se bi vo hieu hoan toan)" {
  can_docker
  run bash -c "{
    printf \"SELECT set_config('qlgx.app_user', 'trung_ten', false);\n\"
    printf \"SELECT set_config('qlgx.admin_user', 'trung_ten', false);\n\"
    cat '${BATS_TEST_DIRNAME}/../../scripts/sql/01-bang-sao-luu-quyen.sql'
  } | docker exec -i '$TEN_CT' psql -v ON_ERROR_STOP=1 -U postgres -d qlgx"
  [ "$status" -ne 0 ]
}
